// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConflictRegion } from "./ConflictRegion";
import type { MultilineString } from "./MultilineString";
import type { RevId } from "./RevId";
import type { TreePath } from "./TreePath";

export interface ConflictResolutionReview { path: TreePath, revision_id: RevId, parent_id: RevId, ours_label: string, theirs_label: string, regions: Array<ConflictRegion>, resolved_content: MultilineString, }