// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConflictRegion } from "./ConflictRegion";
import type { TreePath } from "./TreePath";

export interface ConflictSlicesResponse { path: TreePath, ours_label: string, theirs_label: string, regions: Array<ConflictRegion>, }