// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConflictType } from "./ConflictType";
import type { MultilineString } from "./MultilineString";

export interface ConflictRegion { index: number, conflict_index: number | null, kind: ConflictType, ours: MultilineString, theirs: MultilineString, }